---
kind: pipeline
name: RPM Build EL7

platform:
  os: linux
  arch: amd64

steps:
- name: Build EL7
  image: rancher/dapper:v0.6.0
  commands:
  - make build-centos7
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: Sign RPM EL7
  image: rancher/dapper:v0.6.0
  environment:
    PRIVATE_KEY:
      from_secret: private_key
    PRIVATE_KEY_PASS_PHRASE:
      from_secret: private_key_pass_phrase
    TESTING_PRIVATE_KEY:
      from_secret: testing_private_key
    TESTING_PRIVATE_KEY_PASS_PHRASE:
      from_secret: testing_private_key_pass_phrase
  commands:
  - make sign-centos7
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: Yum Repo Upload EL7
  image: rancher/dapper:v0.6.0
  environment:
    AWS_S3_BUCKET:
      from_secret: aws_s3_bucket
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    TESTING_AWS_S3_BUCKET:
      from_secret: testing_aws_s3_bucket
    TESTING_AWS_ACCESS_KEY_ID:
      from_secret: testing_aws_access_key_id
    TESTING_AWS_SECRET_ACCESS_KEY:
      from_secret: testing_aws_secret_access_key
  commands:
  - make upload-centos7
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: GitHub Release EL7
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-centos7-noarch.txt
    checksum_flatten: true
    files:
    - "dist/centos7/**/*.rpm"
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: RPM Build EL8

platform:
  os: linux
  arch: amd64

steps:
- name: Build EL8
  image: rancher/dapper:v0.6.0
  commands:
  - make build-centos8
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: Sign RPM EL8
  image: rancher/dapper:v0.6.0
  environment:
    PRIVATE_KEY:
      from_secret: private_key
    PRIVATE_KEY_PASS_PHRASE:
      from_secret: private_key_pass_phrase
    TESTING_PRIVATE_KEY:
      from_secret: testing_private_key
    TESTING_PRIVATE_KEY_PASS_PHRASE:
      from_secret: testing_private_key_pass_phrase
  commands:
  - sign-centos8
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: Yum Repo Upload EL8
  image: rancher/dapper:v0.6.0
  environment:
    AWS_S3_BUCKET:
      from_secret: aws_s3_bucket
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    TESTING_AWS_S3_BUCKET:
      from_secret: testing_aws_s3_bucket
    TESTING_AWS_ACCESS_KEY_ID:
      from_secret: testing_aws_access_key_id
    TESTING_AWS_SECRET_ACCESS_KEY:
      from_secret: testing_aws_secret_access_key
  commands:
  - make upload-centos8
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: GitHub Release EL8
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-centos8-noarch.txt
    checksum_flatten: true
    files:
    - "dist/centos8/**/*.rpm"
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: RPM Build SLE Micro

platform:
  os: linux
  arch: amd64

steps:
- name: Build SLE Micro
  image: rancher/dapper:v0.6.0
  commands:
  - make build-slemicro
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: Sign RPM SLE
  image: rancher/dapper:v0.6.0
  environment:
    PRIVATE_KEY:
      from_secret: private_key
    PRIVATE_KEY_PASS_PHRASE:
      from_secret: private_key_pass_phrase
    TESTING_PRIVATE_KEY:
      from_secret: testing_private_key
    TESTING_PRIVATE_KEY_PASS_PHRASE:
      from_secret: testing_private_key_pass_phrase
  commands:
  - make sign-slemicro
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: Yum Repo Upload SLE Micro
  image: rancher/dapper:v0.6.0
  environment:
    AWS_S3_BUCKET:
      from_secret: aws_s3_bucket
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    TESTING_AWS_S3_BUCKET:
      from_secret: testing_aws_s3_bucket
    TESTING_AWS_ACCESS_KEY_ID:
      from_secret: testing_aws_access_key_id
    TESTING_AWS_SECRET_ACCESS_KEY:
      from_secret: testing_aws_secret_access_key
  commands:
  - make upload-slemicro
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: GitHub Release SLE Micro
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-slemicro-noarch.txt
    checksum_flatten: true
    files:
    - "dist/slemicro/**/*.rpm"
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: RPM Build Microos

platform:
  os: linux
  arch: amd64

steps:
- name: Build MicroOS
  image: rancher/dapper:v0.6.0
  commands:
  - make build-microos
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: Sign RPM MicroOS
  image: rancher/dapper:v0.6.0
  environment:
    PRIVATE_KEY:
      from_secret: private_key
    PRIVATE_KEY_PASS_PHRASE:
      from_secret: private_key_pass_phrase
    TESTING_PRIVATE_KEY:
      from_secret: testing_private_key
    TESTING_PRIVATE_KEY_PASS_PHRASE:
      from_secret: testing_private_key_pass_phrase
  commands:
  - make sign-microos
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: Yum Repo Upload MicroOS
  image: rancher/dapper:v0.6.0
  environment:
    AWS_S3_BUCKET:
      from_secret: aws_s3_bucket
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    TESTING_AWS_S3_BUCKET:
      from_secret: testing_aws_s3_bucket
    TESTING_AWS_ACCESS_KEY_ID:
      from_secret: testing_aws_access_key_id
    TESTING_AWS_SECRET_ACCESS_KEY:
      from_secret: testing_aws_secret_access_key
  commands:
  - upload-microos
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: GitHub Release MicroOS
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-microos-noarch.txt
    checksum_flatten: true
    files:
    - "dist/microos/**/*.rpm"
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: RPM Build Fedora CoreOS

platform:
  os: linux
  arch: amd64

steps:
- name: Build Fedora CoreOS
  image: rancher/dapper:v0.6.0
  commands:
  - make build-coreos
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: Sign RPM Fedora CoreOS
  image: rancher/dapper:v0.6.0
  environment:
    PRIVATE_KEY:
      from_secret: private_key
    PRIVATE_KEY_PASS_PHRASE:
      from_secret: private_key_pass_phrase
    TESTING_PRIVATE_KEY:
      from_secret: testing_private_key
    TESTING_PRIVATE_KEY_PASS_PHRASE:
      from_secret: testing_private_key_pass_phrase
  commands:
  - make sign-coreos
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: Yum Repo Upload Fedora CoreOS
  image: rancher/dapper:v0.6.0
  environment:
    AWS_S3_BUCKET:
      from_secret: aws_s3_bucket
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    TESTING_AWS_S3_BUCKET:
      from_secret: testing_aws_s3_bucket
    TESTING_AWS_ACCESS_KEY_ID:
      from_secret: testing_aws_access_key_id
    TESTING_AWS_SECRET_ACCESS_KEY:
      from_secret: testing_aws_secret_access_key
  commands:
  - make upload-coreos
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: GitHub Release Fedora CoreOS
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-coreos-noarch.txt
    checksum_flatten: true
    files:
    - "dist/coreos/**/*.rpm"
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: RPM Build EL9

platform:
  os: linux
  arch: amd64

steps:
- name: Build EL9
  image: rancher/dapper:v0.6.0
  commands:
  - make build-centos9
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: Sign RPM EL9
  image: rancher/dapper:v0.6.0
  environment:
    PRIVATE_KEY:
      from_secret: private_key
    PRIVATE_KEY_PASS_PHRASE:
      from_secret: private_key_pass_phrase
    TESTING_PRIVATE_KEY:
      from_secret: testing_private_key
    TESTING_PRIVATE_KEY_PASS_PHRASE:
      from_secret: testing_private_key_pass_phrase
  commands:
  - make sign-centos9
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: Yum Repo Upload EL9
  image: rancher/dapper:v0.6.0
  environment:
    AWS_S3_BUCKET:
      from_secret: aws_s3_bucket
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    TESTING_AWS_S3_BUCKET:
      from_secret: testing_aws_s3_bucket
    TESTING_AWS_ACCESS_KEY_ID:
      from_secret: testing_aws_access_key_id
    TESTING_AWS_SECRET_ACCESS_KEY:
      from_secret: testing_aws_secret_access_key
  commands:
  - make upload-centos9
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: GitHub Release EL9
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-centos9-noarch.txt
    checksum_flatten: true
    files:
    - "dist/centos9/**/*.rpm"
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock