FROM fedora:43 AS build

RUN yum -y install container-selinux git rpm-build selinux-policy-devel yum-utils

ENV SOURCE=/source

WORKDIR ${SOURCE}

COPY . .

ARG TAG
ARG SCRIPT=build

RUN ${SOURCE}/policy/coreos/scripts/entry "${SCRIPT}"

FROM scratch AS result
ENV SOURCE=/source

COPY --from=build ${SOURCE}/dist /dist
