FROM fedora:40 AS build

RUN find /etc/yum.repos.d -type f -name '*.repo' -exec \
    sed -i -e '/mirrorlist.*/d' -e 's%#baseurl=http://mirror.centos.org%baseurl=http://vault.centos.org%g' {} \;
RUN yum -y install container-selinux git rpm-build selinux-policy-devel yum-utils

ENV SOURCE=/source

WORKDIR ${SOURCE}

COPY . .

ARG TAG
ARG SCRIPT=build

RUN ${SOURCE}/policy/coreos/scripts/entry "${SCRIPT}"

FROM scratch AS result
ENV SOURCE=/source

COPY --from=build ${SOURCE}/dist /dist