#!/bin/bash
set -e -x

cd $(dirname $0)/..
. ./scripts/version

make -f /usr/share/selinux/devel/Makefile k3s.pp

rpmbuild \
    --define "k3s_selinux_version ${RPM_VERSION}" \
    --define "k3s_selinux_release ${RPM_RELEASE}" \
    --define "_sourcedir $PWD" \
    --define "_specdir $PWD" \
    --define "_builddir $PWD" \
    --define "_srcrpmdir ${PWD}/dist/source" \
    --define "_buildrootdir $PWD/.build" \
    --define "_rpmdir ${PWD}/dist" \
    -ba k3s-selinux.spec

#dnf install -y dist/noarch/k3s-selinux-*.rpm
#semodule --disable k3s
#dnf remove k3s-selinux
mkdir -p /source/dist/centos9
cp -r dist/* /source/dist/centos9
