#!/bin/sh
set -ex

if [ -e ./policy/slemicro/scripts/"$1" ]; then
    ./policy/slemicro/scripts/"$@"
else
    exec "$@"
fi

if [ "$DAPPER_UID" -ne "-1" ]; then
  chown -R $DAPPER_UID:$DAPPER_GID .
fi
