#!/bin/bash
set -e -x

pushd $(dirname $0)/..
. ./scripts/version
popd

if [ -z "$RPM_CHANNEL" ]; then
  echo "RPM_CHANNEL not defined, failing rpm upload"
  exit 1
fi

TARGET_EL7_S3_PATH="k3s/$RPM_CHANNEL/common/centos/7/noarch"
TARGET_EL7_SOURCE_S3_PATH="k3s/$RPM_CHANNEL/common/centos/7/source"

TARGET_EL8_S3_PATH="k3s/$RPM_CHANNEL/common/centos/8/noarch"
TARGET_EL8_SOURCE_S3_PATH="k3s/$RPM_CHANNEL/common/centos/8/source"

case "$RPM_CHANNEL" in
  "testing")
    if [ -z "$TESTING_AWS_S3_BUCKET" ]; then
      echo "TESTING_AWS_S3_BUCKET not defined, failing rpm upload"
      exit 1
    fi
    if [ -z "$TESTING_AWS_ACCESS_KEY_ID" ]; then
      echo "TESTING_AWS_ACCESS_KEY_ID not defined, failing rpm upload"
      exit 1
    fi
    if [ -z "$TESTING_AWS_SECRET_ACCESS_KEY" ]; then
      echo "TESTING_AWS_SECRET_ACCESS_KEY not defined, failing rpm upload"
      exit 1
    fi
    export AWS_ACCESS_KEY_ID=$TESTING_AWS_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY=$TESTING_AWS_SECRET_ACCESS_KEY
    export AWS_S3_BUCKET=$TESTING_AWS_S3_BUCKET
    ;;
  "latest"|"stable")
    if [ -z "$AWS_S3_BUCKET" ]; then
      echo "AWS_S3_BUCKET not defined, failing rpm upload"
      exit 1
    fi
    if [ -z "$AWS_ACCESS_KEY_ID" ]; then
      echo "AWS_ACCESS_KEY_ID not defined, failing rpm upload"
      exit 1
    fi
    if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
      echo "AWS_SECRET_ACCESS_KEY not defined, failing rpm upload"
      exit 1
    fi
    ;;
  *)
    echo "RPM_CHANNEL $RPM_CHANNEL does not match one of: [testing, latest, stable]"
    exit 1
    ;;
esac

rpm-s3 --bucket $AWS_S3_BUCKET -p $TARGET_EL7_S3_PATH --keep 100000 dist/rpm/**/k3s-*.rpm
rpm-s3 --bucket $AWS_S3_BUCKET -p $TARGET_EL7_SOURCE_S3_PATH --keep 100000 dist/source/k3s-*src.rpm

rpm-s3 --bucket $AWS_S3_BUCKET -p $TARGET_EL8_S3_PATH --keep 100000 dist/rpm/**/k3s-*.rpm
rpm-s3 --bucket $AWS_S3_BUCKET -p $TARGET_EL8_SOURCE_S3_PATH --keep 100000 dist/source/k3s-*src.rpm
